insert into ref_product (id_product, name) values(1, 'Животноводство');
insert into ref_product (id_product, name) values(2, 'Растениеводство');
insert into ref_product (id_product, name) values(3, 'Продукция из зерна');
insert into ref_product (id_product, name) values(4, 'Прогдовольствие');
insert into ref_product (id_product, name) values(5, 'Сельскохозяйственная техника');
insert into ref_product (id_product, name) values(6, 'Удобрения');
insert into ref_product (id_product, name) values(7, 'Корма и добавки');
insert into ref_product (id_product, name) values(8, 'Посадочный материал');
insert into ref_product (id_product, name) values(9, 'ГСМ');
insert into ref_product (id_product, name) values(10, 'ОБОРУДОВАНИЕ ДЛЯ ПЕРЕРАБОТКИ, УПАКОВКИ И ХРАНЕНИЯ');
insert into ref_product (id_product, name) values(11, 'Спецодежда и спец инвентарь');
insert into ref_product (id_product, name) values(12, 'Средства защиты растений');
insert into ref_product (id_product, name) values(13, 'Тара и упаковка');