package com.onebutton.db.hibernate;
// Generated 17.11.2013 14:13:39 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private int idCustomer;
     private Person person;
     private RefRole refRole;
     private String login;
     private String password;
     private String email;
     private Boolean isDelite;
     private Boolean isActivated;
     private Set<Advert> adverts = new HashSet<Advert>(0);
     private Set<Person> persons = new HashSet<Person>(0);
     private int count;

    public Customer() {
    }

	
    public Customer(int idCustomer) {
        this.idCustomer = idCustomer;
    }
    public Customer(int idCustomer, Person person, RefRole refRole, String login, String password, String email, Boolean isDelite, Boolean isActivated, Set<Advert> adverts, Set<Person> persons) {
       this.idCustomer = idCustomer;
       this.person = person;
       this.refRole = refRole;
       this.login = login;
       this.password = password;
       this.email = email;
       this.isDelite = isDelite;
       this.isActivated = isActivated;
       this.adverts = adverts;
       this.persons = persons;
    }
   
    public int getIdCustomer() {
        return this.idCustomer;
    }
    
    public void setIdCustomer(int idCustomer) {
        this.idCustomer = idCustomer;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public RefRole getRefRole() {
        return this.refRole;
    }
    
    public void setRefRole(RefRole refRole) {
        this.refRole = refRole;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getIsDelite() {
        return this.isDelite;
    }
    
    public void setIsDelite(Boolean isDelite) {
        this.isDelite = isDelite;
    }
    public Boolean getIsActivated() {
        return this.isActivated;
    }
    
    public void setIsActivated(Boolean isActivated) {
        this.isActivated = isActivated;
    }
    public Set<Advert> getAdverts() {
        return this.adverts;
    }
    
    public void setAdverts(Set<Advert> adverts) {
        this.adverts = adverts;
    }
    public Set<Person> getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set<Person> persons) {
        this.persons = persons;
    }




}


