package com.onebutton.db.hibernate;
// Generated 13.10.2013 16:11:27 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

    private int idCustomer;
    private Person person;
    private RefRole refRole;
    private String login;
    private String password;
    private String email;
    private Boolean isDelite;
    private Set adverts = new HashSet(0);
    private Set persons = new HashSet(0);
    private String cryptoKey;

    public Customer() {
    }

    public Customer(int idCustomer) {
        this.idCustomer = idCustomer;
    }

    public Customer(int idCustomer, Person person, RefRole refRole, String login, String password, String email, Boolean isDelite, Set adverts, Set persons) {
        this.idCustomer = idCustomer;
        this.person = person;
        this.refRole = refRole;
        this.login = login;
        this.password = password;
        this.email = email;
        this.isDelite = isDelite;
        this.adverts = adverts;
        this.persons = persons;
    }

    public int getIdCustomer() {
        return this.idCustomer;
    }

    public void setIdCustomer(int idCustomer) {
        this.idCustomer = idCustomer;
    }

    public Person getPerson() {
        return this.person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public RefRole getRefRole() {
        return this.refRole;
    }

    public void setRefRole(RefRole refRole) {
        this.refRole = refRole;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Boolean getIsDelite() {
        return this.isDelite;
    }

    public void setIsDelite(Boolean isDelite) {
        this.isDelite = isDelite;
    }

    public Set getAdverts() {
        return this.adverts;
    }

    public void setAdverts(Set adverts) {
        this.adverts = adverts;
    }

    public Set getPersons() {
        return this.persons;
    }

    public void setPersons(Set persons) {
        this.persons = persons;
    }

    public String getCryptoKey() {
        return cryptoKey;
    }

    public void setCryptoKey(String cryptoKey) {
        this.cryptoKey = cryptoKey;
    }

}
