package com.onebutton.db.hibernate;
// Generated 13.10.2013 16:11:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Organization generated by hbm2java
 */
public class Organization  implements java.io.Serializable {


     private int idOrganization;
     private RefArea refArea;
     private String shortNameOrg;
     private String fullNameOrg;
     private Set persons = new HashSet(0);
     private Set adverts = new HashSet(0);

    public Organization() {
    }

	
    public Organization(int idOrganization) {
        this.idOrganization = idOrganization;
    }
    public Organization(int idOrganization, RefArea refArea, String shortNameOrg, String fullNameOrg, Set persons, Set adverts) {
       this.idOrganization = idOrganization;
       this.refArea = refArea;
       this.shortNameOrg = shortNameOrg;
       this.fullNameOrg = fullNameOrg;
       this.persons = persons;
       this.adverts = adverts;
    }
   
    public int getIdOrganization() {
        return this.idOrganization;
    }
    
    public void setIdOrganization(int idOrganization) {
        this.idOrganization = idOrganization;
    }
    public RefArea getRefArea() {
        return this.refArea;
    }
    
    public void setRefArea(RefArea refArea) {
        this.refArea = refArea;
    }
    public String getShortNameOrg() {
        return this.shortNameOrg;
    }
    
    public void setShortNameOrg(String shortNameOrg) {
        this.shortNameOrg = shortNameOrg;
    }
    public String getFullNameOrg() {
        return this.fullNameOrg;
    }
    
    public void setFullNameOrg(String fullNameOrg) {
        this.fullNameOrg = fullNameOrg;
    }
    public Set getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set persons) {
        this.persons = persons;
    }
    public Set getAdverts() {
        return this.adverts;
    }
    
    public void setAdverts(Set adverts) {
        this.adverts = adverts;
    }




}


