package com.onebutton.db.hibernate;
// Generated 17.11.2013 14:13:39 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Organization generated by hbm2java
 */
public class Organization  implements java.io.Serializable {


     private int idOrganization;
     private RefArea refArea;
     private String shortNameOrg;
     private String fullNameOrg;
     private Set<Person> persons = new HashSet<Person>(0);
     private Set<Advert> adverts = new HashSet<Advert>(0);

    public Organization() {
    }

	
    public Organization(int idOrganization) {
        this.idOrganization = idOrganization;
    }
    public Organization(int idOrganization, RefArea refArea, String shortNameOrg, String fullNameOrg, Set<Person> persons, Set<Advert> adverts) {
       this.idOrganization = idOrganization;
       this.refArea = refArea;
       this.shortNameOrg = shortNameOrg;
       this.fullNameOrg = fullNameOrg;
       this.persons = persons;
       this.adverts = adverts;
    }
   
    public int getIdOrganization() {
        return this.idOrganization;
    }
    
    public void setIdOrganization(int idOrganization) {
        this.idOrganization = idOrganization;
    }
    public RefArea getRefArea() {
        return this.refArea;
    }
    
    public void setRefArea(RefArea refArea) {
        this.refArea = refArea;
    }
    public String getShortNameOrg() {
        return this.shortNameOrg;
    }
    
    public void setShortNameOrg(String shortNameOrg) {
        this.shortNameOrg = shortNameOrg;
    }
    public String getFullNameOrg() {
        return this.fullNameOrg;
    }
    
    public void setFullNameOrg(String fullNameOrg) {
        this.fullNameOrg = fullNameOrg;
    }
    public Set<Person> getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set<Person> persons) {
        this.persons = persons;
    }
    public Set<Advert> getAdverts() {
        return this.adverts;
    }
    
    public void setAdverts(Set<Advert> adverts) {
        this.adverts = adverts;
    }




}


