package com.onebutton.db.hibernate;
// Generated 13.10.2013 16:11:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private int idPerson;
     private Organization organization;
     private Customer customer;
     private String name;
     private String surname;
     private String patrenemic;
     private Set customers = new HashSet(0);
     private Set telephones = new HashSet(0);

    public Person() {
    }

	
    public Person(int idPerson) {
        this.idPerson = idPerson;
    }
    public Person(int idPerson, Organization organization, Customer customer, String name, String surname, String patrenemic, Set customers, Set telephones) {
       this.idPerson = idPerson;
       this.organization = organization;
       this.customer = customer;
       this.name = name;
       this.surname = surname;
       this.patrenemic = patrenemic;
       this.customers = customers;
       this.telephones = telephones;
    }
   
    public int getIdPerson() {
        return this.idPerson;
    }
    
    public void setIdPerson(int idPerson) {
        this.idPerson = idPerson;
    }
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getPatrenemic() {
        return this.patrenemic;
    }
    
    public void setPatrenemic(String patrenemic) {
        this.patrenemic = patrenemic;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }
    public Set getTelephones() {
        return this.telephones;
    }
    
    public void setTelephones(Set telephones) {
        this.telephones = telephones;
    }




}


