package com.onebutton.db.hibernate;
// Generated 17.11.2013 14:13:39 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RefArea generated by hbm2java
 */
public class RefArea  implements java.io.Serializable {


     private int idArea;
     private String name;
     private Set<Advert> adverts = new HashSet<Advert>(0);
     private Set<Organization> organizations = new HashSet<Organization>(0);

    public RefArea() {
    }

	
    public RefArea(int idArea) {
        this.idArea = idArea;
    }
    public RefArea(int idArea, String name, Set<Advert> adverts, Set<Organization> organizations) {
       this.idArea = idArea;
       this.name = name;
       this.adverts = adverts;
       this.organizations = organizations;
    }
   
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Advert> getAdverts() {
        return this.adverts;
    }
    
    public void setAdverts(Set<Advert> adverts) {
        this.adverts = adverts;
    }
    public Set<Organization> getOrganizations() {
        return this.organizations;
    }
    
    public void setOrganizations(Set<Organization> organizations) {
        this.organizations = organizations;
    }




}


