package com.onebutton.db.hibernate;
// Generated 13.10.2013 16:11:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RefArea generated by hbm2java
 */
public class RefArea  implements java.io.Serializable {


     private int idArea;
     private String name;
     private Set adverts = new HashSet(0);
     private Set organizations = new HashSet(0);

    public RefArea() {
    }

	
    public RefArea(int idArea) {
        this.idArea = idArea;
    }
    public RefArea(int idArea, String name, Set adverts, Set organizations) {
       this.idArea = idArea;
       this.name = name;
       this.adverts = adverts;
       this.organizations = organizations;
    }
   
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getAdverts() {
        return this.adverts;
    }
    
    public void setAdverts(Set adverts) {
        this.adverts = adverts;
    }
    public Set getOrganizations() {
        return this.organizations;
    }
    
    public void setOrganizations(Set organizations) {
        this.organizations = organizations;
    }




}


