package com.onebutton.db.hibernate;
// Generated 13.10.2013 16:11:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RefActual generated by hbm2java
 */
public class RefActual  implements java.io.Serializable {


     private int idActual;
     private String name;
     private Set statAdvertActualities = new HashSet(0);

    public RefActual() {
    }

	
    public RefActual(int idActual) {
        this.idActual = idActual;
    }
    public RefActual(int idActual, String name, Set statAdvertActualities) {
       this.idActual = idActual;
       this.name = name;
       this.statAdvertActualities = statAdvertActualities;
    }
   
    public int getIdActual() {
        return this.idActual;
    }
    
    public void setIdActual(int idActual) {
        this.idActual = idActual;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getStatAdvertActualities() {
        return this.statAdvertActualities;
    }
    
    public void setStatAdvertActualities(Set statAdvertActualities) {
        this.statAdvertActualities = statAdvertActualities;
    }




}


