package com.onebutton.db.hibernate;
// Generated 13.10.2013 16:11:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RefAdvertType generated by hbm2java
 */
public class RefAdvertType  implements java.io.Serializable {

    private int count;
     private int idAdvType;
     private String name;
     private Set adverts = new HashSet(0);

    public RefAdvertType() {
    }

	
    public RefAdvertType(int idAdvType) {
        this.idAdvType = idAdvType;
    }
    public RefAdvertType(int idAdvType, String name, Set adverts) {
       this.idAdvType = idAdvType;
       this.name = name;
       this.adverts = adverts;
    }
   
    public int getIdAdvType() {
        return this.idAdvType;
    }
    
    public void setIdAdvType(int idAdvType) {
        this.idAdvType = idAdvType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getAdverts() {
        return this.adverts;
    }
    
    public void setAdverts(Set adverts) {
        this.adverts = adverts;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

}


