package com.onebutton.db.hibernate;
// Generated 17.11.2013 14:13:39 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RefActual generated by hbm2java
 */
public class RefActual  implements java.io.Serializable {


     private int idActual;
     private String name;
     private Set<StatAdvertActuality> statAdvertActualities = new HashSet<StatAdvertActuality>(0);

    public RefActual() {
    }

	
    public RefActual(int idActual) {
        this.idActual = idActual;
    }
    public RefActual(int idActual, String name, Set<StatAdvertActuality> statAdvertActualities) {
       this.idActual = idActual;
       this.name = name;
       this.statAdvertActualities = statAdvertActualities;
    }
   
    public int getIdActual() {
        return this.idActual;
    }
    
    public void setIdActual(int idActual) {
        this.idActual = idActual;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<StatAdvertActuality> getStatAdvertActualities() {
        return this.statAdvertActualities;
    }
    
    public void setStatAdvertActualities(Set<StatAdvertActuality> statAdvertActualities) {
        this.statAdvertActualities = statAdvertActualities;
    }




}


