package com.onebutton.db.hibernate;
// Generated 13.10.2013 16:11:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RefProduct generated by hbm2java
 */
public class RefProduct  implements java.io.Serializable {

     private int count;
     private int idProduct;
     private String name;
     private Set adverts = new HashSet(0);

    public RefProduct() {
    }

	
    public RefProduct(int idProduct) {
        this.idProduct = idProduct;
    }
    public RefProduct(int idProduct, String name, Set adverts) {
       this.idProduct = idProduct;
       this.name = name;
       this.adverts = adverts;
    }
   
    public int getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(int idProduct) {
        this.idProduct = idProduct;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getAdverts() {
        return this.adverts;
    }
    
    public void setAdverts(Set adverts) {
        this.adverts = adverts;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }




}


