package com.onebutton.db.hibernate;
// Generated 17.11.2013 14:13:39 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RefRole generated by hbm2java
 */
public class RefRole  implements java.io.Serializable {


     private int idRole;
     private String name;
     private Set<Customer> customers = new HashSet<Customer>(0);

    public RefRole() {
    }

	
    public RefRole(int idRole) {
        this.idRole = idRole;
    }
    public RefRole(int idRole, String name, Set<Customer> customers) {
       this.idRole = idRole;
       this.name = name;
       this.customers = customers;
    }
   
    public int getIdRole() {
        return this.idRole;
    }
    
    public void setIdRole(int idRole) {
        this.idRole = idRole;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }




}


