package com.onebutton.db.hibernate;
// Generated 17.11.2013 14:13:39 by Hibernate Tools 3.2.1.GA



/**
 * RefSmtpAddress generated by hbm2java
 */
public class RefSmtpAddress  implements java.io.Serializable {


     private int idRefSmtpAddress;
     private String domainName;
     private String smtpServerName;

    public RefSmtpAddress() {
    }

	
    public RefSmtpAddress(int idRefSmtpAddress) {
        this.idRefSmtpAddress = idRefSmtpAddress;
    }
    public RefSmtpAddress(int idRefSmtpAddress, String domainName, String smtpServerName) {
       this.idRefSmtpAddress = idRefSmtpAddress;
       this.domainName = domainName;
       this.smtpServerName = smtpServerName;
    }
   
    public int getIdRefSmtpAddress() {
        return this.idRefSmtpAddress;
    }
    
    public void setIdRefSmtpAddress(int idRefSmtpAddress) {
        this.idRefSmtpAddress = idRefSmtpAddress;
    }
    public String getDomainName() {
        return this.domainName;
    }
    
    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }
    public String getSmtpServerName() {
        return this.smtpServerName;
    }
    
    public void setSmtpServerName(String smtpServerName) {
        this.smtpServerName = smtpServerName;
    }




}


