package com.onebutton.db.hibernate;
// Generated 13.10.2013 16:11:27 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * StatAdvertStory generated by hbm2java
 */
public class StatAdvertStory  implements java.io.Serializable {


     private int idAdvStory;
     private Advert advert;
     private RefVolumeType refVolumeType;
     private Date date;
     private Double minPrice;
     private Double maxPrice;
     private Double minVolume;
     private Double maxVolume;
     private Boolean isDelete;

    public StatAdvertStory() {
    }

	
    public StatAdvertStory(int idAdvStory, Advert advert) {
        this.idAdvStory = idAdvStory;
        this.advert = advert;
    }
    public StatAdvertStory(int idAdvStory, Advert advert, RefVolumeType refVolumeType, Date date, Double minPrice, Double maxPrice, Double minVolume, Double maxVolume, Boolean isDelete) {
       this.idAdvStory = idAdvStory;
       this.advert = advert;
       this.refVolumeType = refVolumeType;
       this.date = date;
       this.minPrice = minPrice;
       this.maxPrice = maxPrice;
       this.minVolume = minVolume;
       this.maxVolume = maxVolume;
       this.isDelete = isDelete;
    }
   
    public int getIdAdvStory() {
        return this.idAdvStory;
    }
    
    public void setIdAdvStory(int idAdvStory) {
        this.idAdvStory = idAdvStory;
    }
    public Advert getAdvert() {
        return this.advert;
    }
    
    public void setAdvert(Advert advert) {
        this.advert = advert;
    }
    public RefVolumeType getRefVolumeType() {
        return this.refVolumeType;
    }
    
    public void setRefVolumeType(RefVolumeType refVolumeType) {
        this.refVolumeType = refVolumeType;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getMinPrice() {
        return this.minPrice;
    }
    
    public void setMinPrice(Double minPrice) {
        this.minPrice = minPrice;
    }
    public Double getMaxPrice() {
        return this.maxPrice;
    }
    
    public void setMaxPrice(Double maxPrice) {
        this.maxPrice = maxPrice;
    }
    public Double getMinVolume() {
        return this.minVolume;
    }
    
    public void setMinVolume(Double minVolume) {
        this.minVolume = minVolume;
    }
    public Double getMaxVolume() {
        return this.maxVolume;
    }
    
    public void setMaxVolume(Double maxVolume) {
        this.maxVolume = maxVolume;
    }
    public Boolean getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }




}


