package com.onebutton.db.hibernate;
// Generated 13.10.2013 16:11:27 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * StatAdvertActuality generated by hbm2java
 */
public class StatAdvertActuality  implements java.io.Serializable {


     private int idAdvActuality;
     private Advert advert;
     private RefActual refActual;
     private Date startDate;
     private Date stopDate;
     private Boolean isDelete;

    public StatAdvertActuality() {
    }

	
    public StatAdvertActuality(int idAdvActuality) {
        this.idAdvActuality = idAdvActuality;
    }
    public StatAdvertActuality(int idAdvActuality, Advert advert, RefActual refActual, Date startDate, Date stopDate, Boolean isDelete) {
       this.idAdvActuality = idAdvActuality;
       this.advert = advert;
       this.refActual = refActual;
       this.startDate = startDate;
       this.stopDate = stopDate;
       this.isDelete = isDelete;
    }
   
    public int getIdAdvActuality() {
        return this.idAdvActuality;
    }
    
    public void setIdAdvActuality(int idAdvActuality) {
        this.idAdvActuality = idAdvActuality;
    }
    public Advert getAdvert() {
        return this.advert;
    }
    
    public void setAdvert(Advert advert) {
        this.advert = advert;
    }
    public RefActual getRefActual() {
        return this.refActual;
    }
    
    public void setRefActual(RefActual refActual) {
        this.refActual = refActual;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getStopDate() {
        return this.stopDate;
    }
    
    public void setStopDate(Date stopDate) {
        this.stopDate = stopDate;
    }
    public Boolean getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }




}


