package com.onebutton.db.hibernate;
// Generated 13.10.2013 16:11:27 by Hibernate Tools 3.2.1.GA



/**
 * Telephone generated by hbm2java
 */
public class Telephone  implements java.io.Serializable {


     private int idTel;
     private Person person;
     private String telNumber;

    public Telephone() {
    }

	
    public Telephone(int idTel) {
        this.idTel = idTel;
    }
    public Telephone(int idTel, Person person, String telNumber) {
       this.idTel = idTel;
       this.person = person;
       this.telNumber = telNumber;
    }
   
    public int getIdTel() {
        return this.idTel;
    }
    
    public void setIdTel(int idTel) {
        this.idTel = idTel;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public String getTelNumber() {
        return this.telNumber;
    }
    
    public void setTelNumber(String telNumber) {
        this.telNumber = telNumber;
    }




}


